### PR TITLE
Use of Werkzeug and tfserve console script

### PR DESCRIPTION
**Pull request by gar1t**
Please see the associated commits for details.

### CODE REVIEW

**Comment by iitzco** [comment]
@gar1t , thanks a lot for the contribution! Really appreciate it.

Pull request was merged with a few changes:

- I removed `tfserve.main` console functionality. I'm not sure about providing a console script with `encode`/`decode` defaults and delegate those tasks client side. In cases of inputs with images or audio I think it can get confusing.
- In `helper.py` I went back to print name instead of tensor description. As `tfserve` only needs tensor names, I think the helper must print names only, (although I understand that it can provide extra information such as shape).
- I renamed the endpoints `_ping` and `_shutdown` to `ping` and `shutdown`. I think your idea was to keep them public for testing purposes, but I think it's a great idea to make them public for use.

Now Werkzeug's `run` method is the default. I will be removing `apistar` in next commits.

I will keep an eye on the `tfserve.main` console script and think about it. I will let you know if I finally decide to include it! 

Once again, thanks for the work!

**Comment by iitzco** [comment]
Now [`tfserve 0.2.1`](https://pypi.org/project/tfserve/#history) is out with all these changes.

**Comment by gar1t** [comment]
Awesome - I'm glad it's (mostly) working out!

It's hard to understand why you'd want to pull useful functionality in the CLI. At the very least it lets users run model introspection.

I also don't understand why you'd want to remove useful information about the input/output tensors - such as their shape and type. How is having this information bad? To the contrary, it's indispensable to build the correct encode/decode interface. If you have users who, for some reason that I can't think of, don't want the extra information and cannot tolerate seeing it printed, you can add a `names_only` flag to the function.

As for the default encoding / decoding, again, how is this harmful? If someone doesn't like that they don't have to use it. Are you concerned that the additional main module takes up extra disk space?

I'd like to get behind this project as it's one of the few simple HTTP front ends to TensorFlow models, but the practice of pulling useful, well written and thoroughly tested features from contributors not the best approach for encouraging a community of supporters :)

**Comment by gar1t** [comment]
One way to think about the CLI/main functionality is that it provides an easy-to-use interface to the library. It's not intended to replace the Python API, of course. It's not intended to have the flexibility of the encode/decode Python interface, but it's something you can play around with and even use if you want to adapt your client code accordingly.

One step that you might think about would be the addition of `--encode` and `--decode` command line options. These would be string values that referenced canned encode/decode functions that were provided with the CLI. The implementation that I used might be called `json` for both. That might be used as the default. Another, for `--encode` might be `image`, which expects image bytes in the HTTP request body. More encoder/decoders can be added over time to fill out the support.

So, what I had, spelled out verbosely would be:

    $ tfserve --encode json --decode json

Your concern - that this approach doesn't feel right because it's overfly prescriptive (of course it was never intended to replace the Python interface) - might be addressed with a broader range of encoders/decoders. These would be selected based on what is commonly used, not based on the need to provide a general solution to all possible interfaces (that's what the Python interface is for).

Maybe I have an image classifier. To serve it I'd run:

    $ tfserve --encode image

There's a limit to how flexible the CLI should be. These schemes should only support really obvious use cases. The ability to test a model by sending it JSON is a very obvious use case. The ability to classify an image submitted as a POST body - very obvious use case. Non obvious use cases can be moved over to the Python interface.

**Comment by iitzco** [comment]
@gar1t thanks for the follow up.

> Side note: as I mention in my first PR comment, I was not discarding `tfserver.main`. I wanted to think about some design decisions before integrating this CLI functionality. Let's use this space to discuss this things and move forward with this project!

A couple of things to continue working:

## Respect to tensor names vs tensor info

Users need tensor names in order to make `tfserve` run. `estimate_io_tensors(model_path)` was originally thought (as the `README` mentions) for users that are running a model for which they do not have information about. As they only need the tensor names, I believe that providing extra information (that include the "name" but not in a clear enough way) can be confusing.

For example, user X wants to run the model under `test/`. He has no idea of the graph nodes but he needs the input/output tensor names to make `tfserve` run.

User X runs `estimate_io_tensors` and gets:
```
Possible INPUT tensor names:
        Tensor("import/input:0", dtype=float32)

Possible OUTPUT tensor names:
        Tensor("import/MobilenetV2/Predictions/Reshape/shape:0", shape=(2,), dtype=int32)
        Tensor("import/MobilenetV2/Predictions/Reshape:0", shape=(?, 1001), dtype=float32)
        Tensor("import/MobilenetV2/Predictions/Softmax:0", shape=(?, 1001), dtype=float32)
        Tensor("import/MobilenetV2/Predictions/Shape:0", shape=(2,), dtype=int32)
        Tensor("import/MobilenetV2/Predictions/Reshape_1:0", shape=(?, 1001), dtype=float32)
```

There is no clear clue that the names he must use are those inside brackets.

Instead, if the result is:

```
Possible INPUT tensor names:
        import/input:0

Possible OUTPUT tensor names:
        import/MobilenetV2/Predictions/Reshape/shape:0
        import/MobilenetV2/Predictions/Reshape:0
        import/MobilenetV2/Predictions/Softmax:0
        import/MobilenetV2/Predictions/Shape:0
        import/MobilenetV2/Predictions/Reshape_1:0
```

**I think it's more clear.**

I know that we are clearly not showing very useful information, such as shape. But it's a tradeoff.

A possible solution could be to add a flag (as you propose) with `names_only` as default in `True`. What do you think about this?

## Respect to the CLI

I understand that the CLI is no harmful at all and I also agree that is really well coded and tested.

My main concern is to provide a CLI functionality with limited defaults (`json` encode/decode) only that could make distracted users not consider the python API original functionality. Using the CLI implies that the user must implicitly develop `encode/decode` methods client side. If the user is not aware of the original API and the `encoding` function is not so trivial (for example dealing with text), this could be a key reason for not using `tfserve`. This being said, 

You mention:

> There's a limit to how flexible the CLI should be. These schemes should only support really obvious use cases.

Totally agree. **If we decide to add the CLI (with `json` support only), we should be very careful in the `README` to describe the CLI as an alternative to the original API and not a replacement, so that we do not lose `tfserve` users with non-trivial use cases.**

#### About canned encode/decode

I really like your approach on providing canned encode/decode functions, we could definitely work on it to make the CLI more robust.

I have only one question if we decide to move forward with the CLI: I thought that `feed_dict` values must be `numpy` arrays. From what is says in the official documentation [here](https://www.tensorflow.org/api_docs/python/tf/Session#run), "Each value in feed_dict must be convertible to a numpy array of the dtype of the corresponding key." Does this mean that we can provide python lists as values?

For example, if user wants to provide 5 200x200 RGB images to be executed in batch mode,  is it enough to provide concatenated python native lists of double values?

Based on your implementation (snippet pasted below) this is true and we can directly use `json.loads()` and work with native python lists instead of numpy arrays.

```
    @staticmethod
    def _decode_request(request_bytes):
        if not request_bytes:
            raise BadInput("empty request")
        try:
            return json.loads(request_bytes)
        except json.decoder.JSONDecodeError as e:
            raise BadInput(str(e))
```


Once again, thanks for your follow up! I never intended to pull useful functionality that you develop. I just wanted to discuss some implementation decisions before adding them to `master`.


Wait for your response!

**Comment by gar1t** [comment]
### Getting model info

Regarding graph tensor info, I think this is a matter of formatting. I don't see a trade off. A developer needs the names *and also needs the shapes and types*. TFServe is *not* just asking for names, it's asking for encode/decode logic, which requires knowledge of shapes and types.

I'm not speculating on what's clear and not clear - I can tell you as a user, this information is essential :)

I would suggest at least one change, maybe two.

#### Change 1 - Use "tensors" to describe these in the output and use the default tensor __str__ formatting

E.g. from:

```
Possible INPUT tensor names:
        import/input:0
```

to:

```
Possible INPUT tensors:
        Tensor("import/x:0", shape=(?, 5), dtype=float64)
```

Guiding a developer to provide the value inside the quotes is a matter of documentation. This is a developer API and it's reasonable I think to trust that developers are intelligent enough to identify the name in the output provided.

Note that this uses the default formatting provided by TensorFlow - we're not making up some new syntax. Anyone working with tensors in TensorFlow will have seen many times before.

#### Change 2 (optional) - tweak the formatting to improve readability

We could take a stab at a different output format. E.g.

```
Possible INPUT tensors:
  name        shape  dtype
  import/x:0  (?,5)  float64
```

However, before bending over backward like this based on speculation, I would not bother and wait until someone - anyone - expresses confusion about the default tensor format. This change can be added later if and when anyone expresses confusion.

We're discussing a low level programming utility, not an consumer electronics device. We need the info to do the work.

### Additional flags to function

I wouldn't complicate things with `names_only` flags. This is not a complicated problem. Keep it simple.

**Comment by gar1t** [comment]
### CLI vs Python API

There is no trade off between having a CLI and a Python API. They provide solutions to very different use cases, though I agree there's overlap. Whether a developer uses one or another is up to that person. Whether they write encode/decode logic or a REST client, they have to understand programming interfaces and it's reasonable to assume they can decide for themselves what approach they want to take.

Steering a developer toward writing a custom API is a matter of documentation. Not having this CLI because you're concerned that it will undermine the Python API I think it an extreme solution to a non problem. If someone can use the CLI out-of-the-box as a server solution, great! There's no problem there - that's a solution. If that doesn't work, they can write their own encode/decode logic. I think developers doing this work are capable of navigating these paths.

I agree, README content is always helpful. Maybe wrap the section in flashing red WARNING lights ;)

#### JSON encoder

If the current implementation works, I'd just leave it alone. Yes, from what I've seen, TensorFlow is happy with Python lists as inputs. If there's some reason to encode that input differently, we can do that. I wouldn't worry too much about it without feedback from users.

Your example of submitting a bunch of images is a good example of where this JSON interface would be silly. It's good for cases where JSON is the natural input. In cases like binary images, I think a different encoder would probably be better (e.g. something that knows about images).

Consider Google Cloud ML. They have a JSON interface. It's a horribly inefficient interface for some cases, but they have it. I'd guess that nearly every web based inference API uses JSON. So TFServe should do that. Is it the only possible interface for all time? No, of course not :) That's what makes TFServe so awesome - it's a low level interface that can be used implement anything at all (over HTTP in this case). But it also provides out-of-the-box support for a handful of commonly used interfaces.

#### Other CLI interfaces

In addition to the JSON support that was part of the original PR, some other ideas:

- Images from binary/raw HTTP body
- Images from form encoded requests (e.g. a form upload)
- [Google Cloud ML compatible JSON interface](https://cloud.google.com/ml-engine/docs/v1/predict-request)

The later is nice for someone building a client interface to Cloud ML. He can use TFServe, e.g. this way:

    tfserve -m graph.pb --encode cloud-ml --decode cloud-ml

Thinking about this though, it feels a little awkward and maybe should be:

    tfserve -m graph.pb --api cloud-ml

See next section for more on `--api`.

#### Use of `--api` rather than `--encode / --decode`

Maybe consider a single option `--api` that implies an encode/decode combo. The JSON scheme in the PR might be named "default" and be used by default. An "image" api might provide basic support for single or multiple images. "cloud-ml" might implement [this interface](https://cloud.google.com/ml-engine/docs/v1/predict-request).

Other possible names for this option:

    --interface
    --encode-decode

While technically these are separate, in practice I think developers will simply want to know "what's the interface here - the expected input format and the output?" That's just one concept and breaking it into two without a compelling use case is over complicating the CLI.

See next section for thoughts on a developer provided encode/decode option.

#### Developer provided encode/decode over CLI

For developers who want to quickly get started with their own encode/decode logic, we could support a module reference, along this line:

    tfserve --api my_custom_module

So if the CLI sees a string that isn't registered, it tries to load that as a module and looks for `encode` and `decode` functions (or something that's formally defined) and uses those.

**Comment by iitzco** [comment]
Great, lots of clarifications here.

## Tensor information

I really like this approach:

```
Possible INPUT tensors:
  name        shape  dtype
  import/x:0  (?,5)  float64
```

Even better than the first one. Let's move right away to implement it.

## CLI

Let's add the `json` interface and start implementing at least the image interface (receiving the image as binary data in HTTP body).

If you want, submit another PR with the json CLI functionality. After all, it was your work.

## Future work 

I will probably start adding some issues around these:

- As we continue adding more functionality, I think the README will become a little bit vague. **A documentation site would be great**.
- Thinking about `tfserve` as a production inference engine, I wonder how Werkzeug deals with the `TFServeApp` object (that contains the `sess` and `graph`) with multiple workers/threads/procceses/etc.

## Side thread

Do you have any ideas on how to spread `tfserve` in order to get more users?

**Comment by gar1t** [comment]
Sounds good! I'll get another PR for the CLI.

**Comment by gar1t** [comment]
@iitzco What a good IM channel for you?

**Pull request merged**
